### ISSUE TITLE
cannot resolve module fs

### ISSUE THREAD

**Issue by frob** [simme/node-yamlhead#4]
ERROR in ./~/yamlhead/yamlhead.js
Module not found: Error: Cannot resolve module 'fs'

**Comment by simme** [comment]
Thank you for this extremely detailed bug report.

`fs` is a core node module, if it can't be found I'd guess something with your setup is broken.

**Comment by frob** [comment]
Do you have any ideas as to what might be wrong with my setup that would cause fs not to load. I am using this with module that is loaded with webpack.

Using node v5.0.0

Are there any other details that you might need to attempt to help me with this bug?

**Comment by simme** [comment]
I assume webpack would have to provide some sort of "shim" for `fs`. Since it seems like you're running this code in the browser you're not actually executing it in a Node environment. This module is not built with the intent of running in the browser. But extracting the code that does the actual parsing should be fairly simple.

**Comment by frob** [comment]
That is interesting, I had assumed that because the error was coming from the node console that it was node firing the error, I guess it is possible that webpack is interrupting it somewhere. 

Seeing as how this module hasn't been updated in over 3 years I thought there might be an api incompatibility with the latest node.
